twig:
    file_name_pattern: '*.twig'
    globals:
        uploaderHelper: '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
    exception_controller: null
    default_path: '%kernel.project_dir%/templates'
        
when@test:
    twig:
        autoescape: true
        strict_variables: true
