twig:
    file_name_pattern: '*.twig'
    globals:
        uploaderHelper: '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
        
when@test:
    twig:
        autoescape: true
        strict_variables: true
