vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_avatar_file:
            uri_prefix: /uploads/images/users/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/images/users/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        animal_file:
            uri_prefix: /uploads/images/animals
            upload_destination: '%kernel.project_dir%/public/uploads/images/animals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        habitat_file:
            uri_prefix: /uploads/images/habitats
            upload_destination: '%kernel.project_dir%/public/uploads/images/habitats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
