vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_avatar:
            uri_prefix: /uploads/images/users/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/images/users/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    