version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: zoo_arcadia
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/Studi/Projet-ECF/Zoo-Arcadia-Back

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html/Studi/Projet-ECF/Zoo-Arcadia-Back
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db-data: